services:
  postgres:
    image: postgres:16
    container_name: elearning_postgres
    environment:
      POSTGRES_USER: elearning_user
      POSTGRES_PASSWORD: elearning_pass
      POSTGRES_DB: elearning_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - elearning_network

  redis:
    image: redis:7
    container_name: elearning_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - elearning_network

  api:
    build: .
    container_name: elearning_api
    depends_on:
      - postgres
      - redis
    environment:
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=elearning_db;Username=elearning_user;Password=elearning_pass"
      Redis__Host: "redis"
      ASPNETCORE_URLS: "http://0.0.0.0:5171"
      ASPNETCORE_ENVIRONMENT: "Test"
    ports:
      - "5171:5171"
    networks:
      - elearning_network
    command: [ "dotnet", "run" ]

  upload-config-files:
    build: ./configuration
    depends_on:
      - postgres
    networks:
      - elearning_network
    environment:
      POSTGRES_USER: elearning_user
      POSTGRES_PASSWORD: elearning_pass
      POSTGRES_DB: elearning_db
      POSTGRES_HOST: elearning_postgres
    restart: "no"
    command: >
      sh -c "
        node /app/upload-to-db.js
      "

volumes:
  postgres_data:
  redis_data:

networks:
  elearning_network:
    driver: bridge
