name: Postman

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  api-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Docker Compose
        run: sudo apt-get update && sudo apt-get install -y docker-compose

      - name: Start API with Docker Compose
        run: docker-compose -f docker-compose.test.yml up -d

      - name: Install Postman CLI
        run: curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh

      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}

      - name: Run API tests
        run: |
          postman collection run "33345036-f08fe69e-b63f-4fd3-ab02-0d44d4288334" -e "33345036-a883de81-e883-4103-8dd3-667f0547d827"

      - name: Stop containers
        run: docker-compose -f docker-compose.test.yml down
